### ISSUE TITLE
netif/slipif.h missing

### ISSUE THREAD

**Issue by marc40000** [martin-ger/esp_slip_router#2]
I'm trying to build this projects with the current open_esp_sdk. I first got an error about ets_isr_t not being defined. I think I got around it by just removing that case in softuart.c

Afterwards, it complains about not being able to find netif/slipif.h . I can't find such a file in the open_esp_sdk and this project. How do I get this file?

**Comment by martin-ger** [comment]
You find it in my esp-open-lwip project https://github.com/martin-ger/esp-open-lwip/tree/sdk-1.5.0/include/netif .
Think, I should add it here.
