### ISSUE TITLE
SSH to esp when there are multiple connections

### ISSUE THREAD

**Issue by domas94** [martin-ger/esp_slip_router#20]
Hi Martin,

I will try to describe my problem once more, because I tried everything I could and couldn't get the solution. 

I used a classic raspberryPi3 and connected it to the same network with ethernet and WIFI. With that setup I could successfully SSH simultaneously to ethernet IP and WIFI IP address.

When I try to do the same with ethernet and slip ESP I get an error. SSH will only work on ethernet IP until I disconnect ethernet cable from the raspberry. It seems to me that the problem is because SLIP IP 192.168.240.2 doesn't belong to the network id where ethernet is connected. Because when I do

sudo ip route add 192.168.254.0/24 via 192.168.240.1

The SSH starts to work for the slip IP, but breaks for the ethernet IP. If I set the metric of sl0 higher than the metric of eth0, eth0 will start to work again, and vice versa.

Thank you for your time.

**Comment by martin-ger** [comment]
It simply doesn't make sense to have two interfaces with different IP addresses from the same sub-network in different layer 2 networks. If you want to build a bridge, you will need a bridge device with one IP addess.

What do you want to achieve?

**Comment by domas94** [comment]
I am developing software for an IoT gateway with RaspberryPi3 Compute module. It is important for us to SSH through WiFi since gateways are usually placed somewhere where they are hard to reach. I also tried SSH to WiFi when it is on a different sub-network that the ethernet. And again I had the same problem. WiFi was connected through mobile hotspot network, and ethernet on my private home network. SSH through WiFi started to work only when I disconnected ethernet cable.

**Comment by martin-ger** [comment]
Could you send me a network plan with IP addess-ranges?

**Comment by domas94** [comment]
![espShow](https://user-images.githubusercontent.com/31627043/114266526-100a1480-99f7-11eb-8e16-91ab260e3634.PNG)
![route with ethernet](https://user-images.githubusercontent.com/31627043/114266539-21532100-99f7-11eb-9d7d-e43a0be395a0.PNG)
![lowered sl0 metric](https://user-images.githubusercontent.com/31627043/114266545-2617d500-99f7-11eb-9a46-d20f461d980b.PNG)

I managed to ssh to raspberry via windows pc when I set the metric of sl0 lower than eth0. Only when sl0 and eth0 are on different networks.

**Comment by domas94** [comment]
![network map](https://user-images.githubusercontent.com/31627043/114267387-80b33000-99fb-11eb-87b5-1117e08e6f3f.PNG)
This is my network map

**Comment by martin-ger** [comment]
When you set the default route on the raspi to 192.168.240.1 it should work, doesn't it?

You can also try just to set the route to the 192.168.126.0/24 net via  192.168.240.1 and leave 192.168.1.1 the default for anything else.

**Comment by domas94** [comment]
If I add 192.168.126.0/24 net via 192.168.240.1 it works even if the sl0 metric is higher than eth0. I guess this should be ok for our purposes. Thank you once again for your help.
