### ISSUE TITLE
Did someone rewrite this to use RTL8720DN?

### ISSUE THREAD

**Issue by Vaklin** [martin-ger/esp_slip_router#22]
Hi!

The idea about slip router is great itself. This looks to be the only solution for my thermal camera for drone project. Important thing is that remote controller works on 5.8GHz only, so the camera down-link should be on this frequency. RTL8720DN as BW16 module is a good candidate for this task. To not discover the round shape from me one more time is much better to ask if someone did this thing to work on the BW16. If no one, I'll try to do it. But first to ask...

Regards...

**Comment by martin-ger** [comment]
I am not aware of an RTL8720DN implementation.
