### ISSUE TITLE
Creating portmaps for port ranges (or 1-to-1 NAT, etc)

### ISSUE THREAD

**Issue by irrationalforest** [martin-ger/esp_slip_router#27]
Hi there!

This is a fantastic project, thank you for writing it.
It has helped get many vintage computers that don't have NICs online.

I am wondering if there is any (undocumented?) way to add a portmap for a range of ports, or even all ports (complete 1-to-1 NAT style) rather than one at a time?

This is useful in situations such as running an FTP server on a machine, where the passive port range is typically at least 256 ports in size.
I have tried inputting a large number of portmaps, one after another, using Expect. The esp_slip_router config seems to hit a maximum limit and stop accepting new portmaps.
Various other commands have also been tried, somewhat blindly:

portmap add TCP 0 192.168.240.2 0
portmap add TCP all 192.168.240.2 all
portmap add TCP any 192.168.240.2 any

These are all accepted, but do not function. :)

Thank you again for your hard work.

Kind regards,
Dominic

**Comment by martin-ger** [comment]
There is no implemented way to do this, but ist using FTP active not an option?

Am 20. Juli 2022 11:46:10 schrieb irrationalforest ***@***.***>:

**Comment by irrationalforest** [comment]
Hi Martin,

Thank you for the reply. Yes, using Active definitely does work.
I was hoping to use Passive since it allows others to access the FTP server without the need for re-configuration and a dedicated FTP client. Eg, using Windows Explorer.
That's OK, I'll find a way to get them using FileZilla in Active mode.
Thanks. :)

Kind regards,
Dominic Ashfield
