### ISSUE TITLE
60 to 70% packet loss?

### ISSUE THREAD

**Issue by sardaukar** [martin-ger/esp_slip_router#8]
I'm seeing huge packet loss on my ESP8266 with this firmware, even when the SLIP interface is not active. Does increasing the CPU speed help? Is my chip broken?

**Comment by martin-ger** [comment]
160 MHz helps. But what do you mean: without SLIP Interface working? What do you measure?

**Comment by sardaukar** [comment]
I'm just pinging the external IP it gets from my WiFi router, even before I do `slattach`

**Comment by martin-ger** [comment]
Should work without any perfomance degradation. Some RF-problem?

Am 10. Juni 2019 16:57:09 schrieb Bruno Antunes <notifications@github.com>:

**Comment by sardaukar** [comment]
Yep, thanks for pointing that out! The case I put the ESP in is an RF blocker :( Will have to work around it.
